### ISSUE TITLE
Basic Attention Token (BAT)

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/Auditing#191]
# Audit request

Audit Top 200 CoinMarketCap tokens.

Basic Attention Token | BAT
--|--
Circulating Supply | 1 244 766 783
Total Supply | 1 500 000 000

https://basicattentiontoken.org/

Deployed at https://etherscan.io/address/0x0d8775f648430679a709e98d2b0cb6250d2887ef#code

# Source code

https://gist.github.com/yuriy77k/9f8fcc78745cf81e3aff92da724b3d5c

# Disclosure policy

Public

# Platform

ETH

# Number of lines 

129

**Comment by MrCrambo** [comment]
Auditing time 1 day

**Comment by yuriy77k** [comment]
@MrCrambo assigned

**Comment by danbogd** [comment]
Auditing time: 2 days.

**Comment by yuriy77k** [comment]
@danbogd assigned

**Comment by danbogd** [comment]
My report is finished.

**Comment by gorbunovperm** [comment]
Estimated auditing time is 2 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned

**Comment by gorbunovperm** [comment]
My report is finished.

**Comment by yuriy77k** [comment]
# Security Audit Report

# 1. Summary

[Basic Attention Token (BAT)](https://etherscan.io/address/0x0d8775f648430679a709e98d2b0cb6250d2887ef#code) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 2. In scope

- [BAToken.sol](https://gist.github.com/yuriy77k/9f8fcc78745cf81e3aff92da724b3d5c#file-batoken-sol)

# 3. Findings

In total, **4 issues** were reported including:

- 1 medium severity issues.

- 3 low severity issues.

No critical security issues were found.

## 3.1. Known vulnerabilities of ERC-20 token

### Severity: low

### Description

1. It is possible to double withdrawal attack. More details [here](https://docs.google.com/document/d/1YLPtQxZu1UAvO9cZ1O2RPXBbT0mooh4DYKjA_jp-RLM/edit).

2. Lack of transaction handling mechanism issue. [WARNING!](https://gist.github.com/Dexaran/ddb3e89fe64bf2e06ed15fbd5679bd20)  This is a very common issue and it already caused millions of dollars losses for lots of token users! More details [here](https://docs.google.com/document/d/1Feh5sP6oQL1-1NHi-X1dbgT3ch2WdhbXRevDN681Jv4/edit).

### Recommendation

Add the following code to the `transfer(_to address, ...)` function:

```
require( _to != address(this) );

```

## 3.2. ERC20 Compliance — transfer should `throw`

### Severity: medium

### Description


From ERC-20 specification:
> The function SHOULD `throw` if the `_from` account balance does not have enough tokens to spend.

But in this implementation of `transfer` and `transferFrom` it just returns `false`. This can lead to serious consequences. Because checking the return value of this function is rare.
For example, external contract may use this token contract as:
```solidity
BatToken.transferFrom(recipient, this, value);
points[recipient] += value;
```
In this case recipient can get any value of points, but he may not have enough money and the code will succeed.

### Code snippet

https://gist.github.com/yuriy77k/9f8fcc78745cf81e3aff92da724b3d5c#file-batoken-sol-L54

https://gist.github.com/yuriy77k/9f8fcc78745cf81e3aff92da724b3d5c#file-batoken-sol-L66

## 3.3. ERC20 Compliance — zero-value transfers rejecting

### Severity: low

### Description

EIP20 says that:
> Transfers of 0 values MUST be treated as normal transfers and fire the Transfer event.
But in this contract, function `transfer` and `transferFrom` has a condition:
```solidity
if (balances[msg.sender] >= _value && _value > 0) {
    // ...
}
```

### Code snippet

https://gist.github.com/yuriy77k/9f8fcc78745cf81e3aff92da724b3d5c#file-batoken-sol-L48

https://gist.github.com/yuriy77k/9f8fcc78745cf81e3aff92da724b3d5c#file-batoken-sol-L59

## 3.4. ERC20 Compliance — event missing

### Severity: low

### Description

1. According to ERC20 standard when coins are minted a `Transfer` event should be emitted.

2. The `createTokens` function also should emit the `Transfer` event.

### Code snippet

https://gist.github.com/yuriy77k/9f8fcc78745cf81e3aff92da724b3d5c#file-batoken-sol-L127

https://gist.github.com/yuriy77k/9f8fcc78745cf81e3aff92da724b3d5c#file-batoken-sol-L145


# 4. Conclusion

The audited smart contract has some issues with ERC20 Compliance that could cause losing the money in a particular situation. We recommend fixing these issues.

# 5. Revealing audit reports

https://gist.github.com/yuriy77k/3ed8070ea3428c085ff2b41d015f92ba

https://gist.github.com/yuriy77k/24e1f3af18913586b8cbddc5338eb68f

https://gist.github.com/yuriy77k/f3ea10397d674838538698e1249048ea

**Comment by diracdeltas** [comment]
Here's a response from @locklin (main creator of the BAT contract) and @mrose17

## response to ["audit"](https://github.com/EthereumCommonwealth/Auditing/issues/191#issuecomment-478635693)

# 3.2. ERC20 Compliance — transfer should throw

> From ERC-20 specification:

>>The function SHOULD throw if the _from account balance does not have enough tokens to spend.

>But in this implementation of transfer and transferFrom it just returns false. This can lead to serious consequences. Because checking the return value of this function is rare.

## response

The [present day EIP20 document](https://eips.ethereum.org/EIPS/eip-20) referenced in this "audit" is a document dating from July of 2017 (aka post crowdsale). It actually says the following:

>transfer

>Transfers _value amount of tokens to address _to, and MUST fire the Transfer event. The function SHOULD throw if the message caller’s account balance does not have enough tokens to spend.

>Note Transfers of 0 values MUST be treated as normal transfers and fire the Transfer event.

SHOULD is not a part of the standard. MUST is a part of the standard.

If someone should write a smart contract which loses tokens, this SHOULD be considered operator error rather than an error in the token contract.

Note that this suggestion is NOT made for transferFrom, which is the assertion of the reviewer. Any implied suggestion or requirement that transferFrom should throw is not in the standard.

More importantly, the actual [ERC20 standard](https://github.com/ethereum/eips/issues/20) published at the time of the deployment of BAT in late May of 2017 says nothing of the sort. The use of logical returns rather than throws in transfer and transferFrom was the standard used in most implementations of ERC20 at the time. For example, the contemporary [ConsenSys ERC20 smart contract](https://github.com/ConsenSys/Tokens/blob/4e21012f98afb0aca5f131cf296fc532560ee601/Token_Contracts/contracts/StandardToken.sol), which BAT was based on, and which was listed as an example implementation of the ERC20 standard in the [original eip-20 document](https://github.com/ethereum/EIPs/blob/7e6905c221cf59067f9e1727026155fcf0f0efb1/EIPS/eip-20-token-standard.md) Revisionist history is not helpful. Any developer who wants to create general purpose ERC20 compliant smart contracts must consider implementation details which fall within the standard; particularly in the case where commonly used contracts have the same implementation detail.


# 3.1. Known vulnerabilities of ERC-20 token

These are known vulnerabilities of the ERC-20 standard. [One of them](https://docs.google.com/document/d/1YLPtQxZu1UAvO9cZ1O2RPXBbT0mooh4DYKjA_jp-RLM/edit) was known at the time of deploy; there is no solution to it, including the listed advice.

The [other issue](https://docs.google.com/document/d/1Feh5sP6oQL1-1NHi-X1dbgT3ch2WdhbXRevDN681Jv4/edit), or collection of issues was unknown at the time of contract deploy, and the suggested fix

>require( _to != address(this) );

would only correct the trivial case where the token is sent to its own token contract. Any other non-handling contract would absorb the tokens forever, just as sending the tokens to 0x would effectively burn them. The numbers of misuses of a technology like an ERC20 token are infinite.

# 3.3. ERC20 Compliance — zero-value transfers rejecting

>EIP20 says that:

>>Transfers of 0 values MUST be treated as normal transfers and fire the Transfer event.
>>But in this contract, function transfer and transferFrom has a condition:

zero-value transfers are now indeed considered to be part of the ERC20 standard. Again, it was not a part of the standard at the time BAT was deployed. There are also effectively no side effects, other than null "Transfer" events are not recorded.
