### ISSUE TITLE
MZBoss smart contract_v2 (casino share)

### ISSUE THREAD

**Issue by Mizhentaotuo** [EthereumCommonwealth/Auditing#22]
# Audit request

Audit request
The smart contract is share of a casino with a token name of MZBoss. The total number of MZBoss is 21000000. The price of MZBoss is constant at 0.00005 ether. The purchase fee is 15%, pay when customers buy MZBoss. There is not fee for selling MZBoss back to the contract, but 15% fee is charged when people sell it to others. The fee is evenly distributed to the existing MZBoss holders. All MZBoss holders will receive profit from different game pots which will be developed soon. An exchange will open so people can exchange MZBoss freely without the price limitation in the smart contract.

Information about updates is in the contract.

# Source code

https://gist.github.com/Mizhentaotuo/49615f7ef06750ebb4e1f2a54593f128

# Disclosure policy

Please notify me privately in case of finding critical mistakes.
whitelmz@hotmail.com

# Platform

ETH

**Comment by pro100skm** [comment]
Auditing time - 4 days

**Comment by MrCrambo** [comment]
Auditing time 4 days

**Comment by yuriy77k** [comment]
@pro100skm @MrCrambo assigned

**Comment by RideSolo** [comment]
Auditing time: 3 days.

**Comment by yuriy77k** [comment]
@RideSolo assigned

**Comment by yuriy77k** [comment]
Contract contain high security issues. Report was send to developer.

**Comment by yuriy77k** [comment]
## @RideSolo

Good job.


## @MrCrambo 

Notes regarding the https://gist.github.com/MrCrambo/c134d1ce67d415d2d7535e8d978492d6 report.

* [1](https://gist.github.com/MrCrambo/c134d1ce67d415d2d7535e8d978492d6#1-wrong-condition) condition in not wrong, because to buy token, ambassador needs to send Ether to contract. So `totalEthereumBalance()` return contract balance including current payment in Ether. Not a security issue.

* [2. No need of casting to int256](https://gist.github.com/MrCrambo/c134d1ce67d415d2d7535e8d978492d6#2-no-need-of-casting-to-int256) it can not cause any problem, so its not a security issue.

* [3. Return nothing.](https://gist.github.com/MrCrambo/c134d1ce67d415d2d7535e8d978492d6#3-return-nothing) You have not specified a function.

**You did not find any security issues, please, do the audit more carefully.**


## @pro100skm

Notes regarding the https://gist.github.com/pro100skm/9b7a28d46a94b4eefc0edb9002b4ebf1 report.

* [1](https://gist.github.com/pro100skm/9b7a28d46a94b4eefc0edb9002b4ebf1#1-wrong-condition) condition in not wrong. It checks to see if the ambassador has reached a quota for purchase. Not a security issue.

**You did not find any security issues, please, do the audit more carefully.**

**Comment by yuriy77k** [comment]
# [MZBoss smart contract_v2](https://gist.github.com/Mizhentaotuo/49615f7ef06750ebb4e1f2a54593f128) security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 1. Conclusion:

The current contract version is not safe to be deployed, multiple high severity issues were highlighted.

# 2. High severity issues:

## 2.1. Tokens Purchase

### Severity: High

### Description

Anyone can exploit `purchaseTokens` making the input value of `_amountOfEthereum` not equal to the real `msg.value`. therefore, buying tokens with an `_amountOfEthereum` that he didn't send. There is no condition checking if `_amountOfEthereum == msg.value`. 
selling the tokens back to the contract will make the attacker able to withdraw ether based on the fake `_amountOfEthereum` that he used.

### Code snippet

https://gist.github.com/Mizhentaotuo/49615f7ef06750ebb4e1f2a54593f128#file-mzboss_v2-L194#L240

## 2.2. Ethereum to Tokens Conversion

### Severity: High

### Description

the conversion does not take into account the decimals, which will lead the users to lose (_ethereum % tokenPriceInitial_) and will return token value without the decimals which will impact many other functions.

### Code snippet

https://gist.github.com/Mizhentaotuo/49615f7ef06750ebb4e1f2a54593f128#file-mzboss_v2-L550#L564

### Recommendation

```
//	tokenPriceInitial_ ---> 10**decimals
//	_ethereum          ---> x

    function ethereumToTokens_(uint256 _ethereum)
        public
        pure
        returns(uint256)
    {
        require (_ethereum > 0);
	uint256 decimals_ = decimals;
        uint256 _tokenPriceInitial = tokenPriceInitial_;
        uint256 _tokensReceived = 
                    SafeMath.div
                    (
                        SafeMath.mul(_ethereum,10**decimals_), 
                        _tokenPriceInitial
                    );
        return _tokensReceived;
    }
```
## 2.3. Tokens to Ethereum Conversion

### Severity: High

### Description

Almost the same conversion mistake as the previous error, in this case the `sell` function will be impacted if the first error is updated.

### Code snippet

https://gist.github.com/Mizhentaotuo/49615f7ef06750ebb4e1f2a54593f128#file-mzboss_v2-L570#L580

### Recommendation
```
//	10**decimals   ---> tokenPriceInitial_
//	_tokens ---> x

     function tokensToEthereum_(uint256 _tokens)
        internal
        pure
        returns(uint256)
    {   
        uint256 tokens_ = _tokens;
	    uint256 decimals_ = decimals;
        uint256 _etherReceived =
	        SafeMath.div(
		        SafeMath.mul (tokenPriceInitial_, tokens_),
		        10**decimals_
	        )
        return _etherReceived;
    }
```

# 3. Medium severity issues:

## 3.1. Dividends Computation

### Description

After multiple tests, the dividends computation has given erroneous output. in a special case a user was not able to sell & withdraw his ether since the [`dividendsOf`](https://gist.github.com/Mizhentaotuo/49615f7ef06750ebb4e1f2a54593f128#file-mzboss_v2-L421) was returning a value higher than the contract balance. the device should review the dividends computation mechanism (the test case is described below).

Test case: three invesors sent ether to buy tokens, all investors sold and withdraw their balance. The last investors was not able to get hist balance back.


# 4. Low severity issues:

## 4.1. Transaction fee

### Description

When an investor sells his shares a transaction fee is deducted from the ether that he gained, knowing that the transaction fees is paid by the investors when calling any function in the contract. 

The devs should explain the intention of this operation, especially since this fee is not shared between holders but will be lost in the contract.

### Code snippet

https://gist.github.com/Mizhentaotuo/49615f7ef06750ebb4e1f2a54593f128#file-mzboss_v2-L332


# 5. Minor observation:

## 5.1. Profit Addresses

### Description

As per the code, only administrators can set profit addresses, ambassador cannot add profit addresses remove the related comment. 

### Code snippet

https://gist.github.com/Mizhentaotuo/49615f7ef06750ebb4e1f2a54593f128#file-mzboss_v2-L363

## 5.2. Minimum Purchase Limit

### Description

A Minimum purchase limit is set to be 10^20 (100 MZB tokens) for normal investors (not ambassadors), the commented description of the contract does not mention any buy limit.

### Code snippet

https://gist.github.com/Mizhentaotuo/49615f7ef06750ebb4e1f2a54593f128#file-mzboss_v2-L507


## 5.3. No need of casting to int256.

### Description

In lines [276](https://gist.github.com/Mizhentaotuo/49615f7ef06750ebb4e1f2a54593f128#file-mzboss_v2-L276), [340](https://gist.github.com/Mizhentaotuo/49615f7ef06750ebb4e1f2a54593f128#file-mzboss_v2-L340), [536](https://gist.github.com/Mizhentaotuo/49615f7ef06750ebb4e1f2a54593f128#file-mzboss_v2-L536) there is no sense of casting to int256, because return value will be uint256 because of using safeMath library.

### Recommendation

No sense of casting to int256.

## 5.4. Duplicate code

### Severity: minor

### Description

Ducplicated code on lines : [599](https://gist.github.com/Mizhentaotuo/49615f7ef06750ebb4e1f2a54593f128#file-mzboss_v2-L599) and [607](https://gist.github.com/Mizhentaotuo/49615f7ef06750ebb4e1f2a54593f128#file-mzboss_v2-L607)

### Recommendation

Put that line after if-else statement, and remove it inside.



# Revealing audit reports:

https://gist.github.com/yuriy77k/d9e86aa10bf621f00aaa67680850dee7

https://gist.github.com/yuriy77k/0d46d440c794a2e0a299b8506ff78a02

https://gist.github.com/yuriy77k/381591610fd03a84fbcd29b9aeb823f2
