### ISSUE TITLE
Gigzi smart contract (ETH)

### ISSUE THREAD

**Issue by GigziOfficial** [EthereumCommonwealth/Auditing#3]
# Audit request

The smart contract allows the Central Authority (CA) to issue tokens backed by precious metals. There will be 3 types of such regulated tokens: GZS silver, GZG gold, GZP platinum and also one non-regulated token GZB black. Tokens have a changeable tx fee (which is set to 0.2% and may be adjusted during the system functioning for its economy benefit). This tx fee is accumulated on CA account; funds will be used for buying precious metals and issuing corresponding precious metals regulated tokens. All users who hold GZB tokens on their accounts will receive payments in GZG from the CA; a size of the payment will be proportional to the amount of GZB tokens on the account. Payments will be initiated by the CA at the end of a billing period, off-chain. The initial distribution of GZB is performed by ICO.

# Source code

https://github.com/GigziProject/GigziContracts/tree/master/contracts

It's ERC827 standard. We use OpenZeppelin Framework as a basis and need an audit of a custom logic built on top of this framework. Solidity v 0.4.23.

# Disclosure policy

Please send an email to artyom@gigzi.com

# Platform

ETH platform

**Comment by dieselc** [comment]
Auditing time 10 days.

**Comment by yuriy77k** [comment]
Auditing time 8 days.

**Comment by MrCrambo** [comment]
Auditing time 7 days.

**Comment by RideSolo** [comment]
Auditing time 7 days.

**Comment by yuriy77k** [comment]
@MrCrambo assigned.
@RideSolo assigned.

**Comment by yuriy77k** [comment]
@Dexaran will be done, sir.

**Comment by yuriy77k** [comment]
> After the auditor began to check the code, he must create a secret github gist and send it to the auditing manager by email. 

@MrCrambo and @RideSolo   send me your gist to email: yuriy77k@gmail.com

**Comment by gorbunovperm** [comment]
Estimated audit time is 6 days.

**Comment by yuriy77k** [comment]
@gorbunovperm assigned.

**Comment by MrCrambo** [comment]
@yuriy77k audit report done!

**Comment by yuriy77k** [comment]
@MrCrambo correct inaccuracies in your report

**Comment by alexo18** [comment]
Estimated audit time is 4 days

**Comment by yuriy77k** [comment]
@alexo18 assigned.

**Comment by MrCrambo** [comment]
@yuriy77k done!

**Comment by alexo18** [comment]
@yuriy77k audit report done.

**Comment by gorbunovperm** [comment]
Hi, Yuriy!

I'm writing to inform you. My report will be finished in a several hours.


-- 
Горбунов Александр.

**Comment by gorbunovperm** [comment]
@yuriy77k my report is ready.

**Comment by gorbunovperm** [comment]
@yuriy77k my report is complete.

**Comment by yuriy77k** [comment]
# Gigzi smart contract security audit conclusion: bug fixing is necessary.

## Critical issue:

* [Fees Avoidance](https://gist.github.com/RideSolo/55e07505b231f1cab7454d21ca8f8dc3#31-fees-avoidance). User can direct call ```transferFromAndCall``` or ```transferAndCall``` implemented in openzepplin ```ERC827Token``` to transfer token without fee collection and possible manipulation of the reward since it the reward won't be updated.


## Medium severity issues:

* ```FeeableToken``` contract overload ```transfer``` and ```transferFrom``` methods, if a user directly call these functions to transfer tokens, it can lead to [lost tokens](https://gist.github.com/RideSolo/55e07505b231f1cab7454d21ca8f8dc3#32-lost-tokens) issue.

* The account reward was updated after subtracting the burned tokens and that [cause lower reward then must be](https://gist.github.com/RideSolo/55e07505b231f1cab7454d21ca8f8dc3#34-account-reward-update-error-when-burning-tokens). 

* [Estimation Account Reward in Percent Error](https://gist.github.com/RideSolo/55e07505b231f1cab7454d21ca8f8dc3#35-estimation-account-reward-in-percent-error).

* [Concurrent access to the 'accounts[]' state variable](https://gist.github.com/alexo18/f7014a8e941e81c98871b758196bdad7#3-concurrent-access-to-the-accounts-state-variable-) may cause incorrect indexing.

## Pay attention:

* [Raw call to untrusted contract](https://gist.github.com/alexo18/f7014a8e941e81c98871b758196bdad7#2-raw-call-to-untrusted-contract)  in [MessageHelper.sol](https://github.com/GigziProject/GigziContracts/blob/master/contracts/helper/MessageHelper.sol#L42) don't hurt Gigzi smart-contract, because it's not used, but you must know about it if you used it in future. 

# Revealing audit reports:

* https://gist.github.com/MrCrambo/422384ecf5a215be81bad6c9b5c2b605
* https://gist.github.com/RideSolo/55e07505b231f1cab7454d21ca8f8dc3
* https://gist.github.com/alexo18/f7014a8e941e81c98871b758196bdad7
* https://gist.github.com/gorbunovperm/0e0fa4e5a532a55672ed68649e51ccb4


## @MrCrambo 

Notes regarding the https://gist.github.com/MrCrambo/422384ecf5a215be81bad6c9b5c2b605 report.

1. [Time](https://gist.github.com/MrCrambo/422384ecf5a215be81bad6c9b5c2b605#1-wrong-calculation-of-reward-in-gigblacksol) in the contract use seconds, not in "millis" and it did not affect on account balance. It used for estimate account reward in percent.

Not a security issue.

2. > All users who hold GZB tokens on their accounts will receive payments in GZG from the CA; a size of the payment will be proportional to the amount of GZB tokens on the account. Payments will be initiated by the CA at the end of a billing period, off-chain. 

So [estimate account reward in percent](https://gist.github.com/MrCrambo/422384ecf5a215be81bad6c9b5c2b605#2-function-getaccountreward-in-gigblacksol-will-calculate-not-with-percent) did not calculate directly in getAccountReward() function, but can calculate off-chain: ```rewardAccum * 100 / supplyTimeTotal``` 

Not a security issue.

3. Modifier [restricted](https://gist.github.com/MrCrambo/422384ecf5a215be81bad6c9b5c2b605#3-modifier-restricted-will-not-work-migrationssol) was correct and no need to change.

Not a security issue.

4. [Math operation](https://gist.github.com/MrCrambo/422384ecf5a215be81bad6c9b5c2b605#4-use-safemath-in-all-operations-gigblacksol) in that lines can not be exploited for over- or under- flow, because it doesn't operate with user inputs. 

Severity: low

### Conclusion

You did not find critical issue. I strongly recommend that you review other audit reports and study the programming of contracts more thoroughly.


## @RideSolo

Notes regarding the https://gist.github.com/RideSolo/55e07505b231f1cab7454d21ca8f8dc3 report.

I have only one note about the [Gas Consumption](https://gist.github.com/RideSolo/55e07505b231f1cab7454d21ca8f8dc3#37-gas-consumption). I agree that gas consumption optimization is very important, but it's not a security issue.

### Conclusion 

Your audit report is fine. You have done an in-depth analysis of the parent contracts from OpenZeppelin.


## @alexo18

Notes regarding the https://gist.github.com/alexo18/f7014a8e941e81c98871b758196bdad7 report.

1. [rewardPeriod](https://gist.github.com/alexo18/f7014a8e941e81c98871b758196bdad7#1-incorrect-calculation-of-the-rewardperiod-parameter) is time period in seconds and no need to any other conversion. 

Not a security issue.

2. [Raw call to untrusted contract](https://gist.github.com/alexo18/f7014a8e941e81c98871b758196bdad7#2-raw-call-to-untrusted-contract)  in [MessageHelper.sol](https://github.com/GigziProject/GigziContracts/blob/master/contracts/helper/MessageHelper.sol#L42) don't hurt Gigzi smart-contract, because it's not used. And it also has  an appropriate comment. 

3. [Concurrent access to the 'accounts[]' state variable](https://gist.github.com/alexo18/f7014a8e941e81c98871b758196bdad7#2-concurrent-access-to-the-accounts-state-variable-) - definitely, this issue make sense, but this is not directly related to this smart-contract. This is more the issue of protocol-level. When compiler crates byte-code it will be almost the same in both variant. 

4. [Flooding attack](https://gist.github.com/alexo18/f7014a8e941e81c98871b758196bdad7#3-potentially-too-large-state-variable) will have high cost attacker but without any profit. It can't affect to contract performance, but affect to blockchain size.  

It is better to assign it low severity.

### Conclusion

You did not find critical issue.


## @gorbunovperm

Notes regarding the https://gist.github.com/gorbunovperm/0e0fa4e5a532a55672ed68649e51ccb4 report.

1. [Lost reward after burning tokens](https://gist.github.com/gorbunovperm/0e0fa4e5a532a55672ed68649e51ccb4#3-the-reward-will-be-lost-after-burning-tokens) - better to assign it medium severity.

### Conclusion

You did not find critical issue.

**Comment by GigziOfficial** [comment]
Hello,

thank you for the professional and good quality review!

We fixed our smart contracts according to your findings.

@Dexaran @yuriy77k 

Is it possible to re-submit our contracts for the second review here?

**Comment by yuriy77k** [comment]
@GigziOfficial I think, you can submit it again.
