### ISSUE TITLE
ERC-20 security audit

### ISSUE THREAD

**Issue by gitr0n1n** [EthereumCommonwealth/Auditing#436]
# Audit request

A generic ERC-20 that needs a contract security audit.

Have Dexaran reach out to me in the ETC Discord or discord Dm to communicate in a more private setting. Thanks

**Comment by Dexaran** [comment]
@gitr0n1n is this still relevant? Honestly I can't understand the purpose of this "request" since you did not provide any source codes that could be audited. The "ERC20 token standard" is not a thing that could be audited because the ERC20 is a formal abstract specification of what a token contract could implement in theory.

**Comment by gitr0n1n** [comment]
No, we hired CertiK to do the audit back in October. Thanks for the response though.
