### ISSUE TITLE
Wildfire

### ISSUE THREAD

**Issue by Wildfire-new** [EthereumCommonwealth/Auditing#500]
# Audit request

... Briefly describe your smart-contract and its main purposes here ...

https://bscscan.com/token/0x3fec64f3c3bb695c001749e6d4e2bbc5c969ceee#balances

# Source code

https://github.com/Wildfire-new/Wildfirebeb20/blob/main/wildfire.sol

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ... yes

... provide your conditions for publishing the report or leave only standard disclosure policy link ... yes

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

Wildfire-NEW@protonmail.com

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

BSC

**Comment by yuriy77k** [comment]
@Wildfire-new what code do you want to audit? From the [Github repository](https://github.com/Wildfire-new/Wildfirebeb20/blob/main/wildfire.sol) or from the [deployed contract](https://bscscan.com/address/0x3fec64f3c3bb695c001749e6d4e2bbc5c969ceee#code)?

**Comment by Wildfire-new** [comment]
Deployed contract

**Comment by yuriy77k** [comment]
@Wildfire-new  The audit fee is 665 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 5 days after payment.

**Comment by Wildfire-new** [comment]
Hey can you Stop the contract, Ma Wallet ist Hacked. Will ne contract creat !

**Comment by yuriy77k** [comment]
> Hey can you Stop the audit contract, Ma Wallet is Hacked. Will new contract creat ! I will re-verify the same contract!

Ok, write here new contract address.

**Comment by yuriy77k** [comment]
# Wildfire Token Security Audit Report

# 1. Summary

[Wildfire (WDF) Token](https://bscscan.com/address/0x6218352Cc511A86F154fe03F69B0aa062e01aeA9#contracts) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

- Telegram https://t.me/WildfireOfficial
- Website https://wildfire-coin.com/

# 2. In scope

https://bscscan.com/address/0x6218352Cc511A86F154fe03F69B0aa062e01aeA9#contracts

# 2.1 Excluded

The correctness of the mathematical calculations was not verified during the audit due to the lack of complete documentation of what the contract should do and under what conditions.


# 3. Findings

In total, **4 issues** were reported including:

- 2 medium severity issues.

- 1 low severity issues.

- 1 owner privileges.


## 3.1. Known vulnerabilities of ERC-20 token

### Severity: low

### Description

1. Lack of transaction handling mechanism issue. [WARNING!](https://gist.github.com/Dexaran/ddb3e89fe64bf2e06ed15fbd5679bd20)  This is a very common issue and it already caused millions of dollars losses for lots of token users! More details [here](https://docs.google.com/document/d/1Feh5sP6oQL1-1NHi-X1dbgT3ch2WdhbXRevDN681Jv4/edit).

### Recommendation

Add the following code to the `transfer(_to address, ...)` function:

```
require( _to != address(this) );

```

2. ERC20 is a widely used standard across the Ethereum ecosystem. It is reasonable to assume that ERC20 tokens could be "accidentally" deposited into this contract even though it is not intentional.

Every user on the entire Ethereum ecosystem can send ERC20 tokens to this contract and he will have no ability to extract it back unless there is a special "ERC20-rescue" function implemented in your contract. It is advised to implement this function.

*Example: here is [BAT contract address](https://etherscan.io/address/0x0d8775f648430679a709e98d2b0cb6250d2887ef). As you can see the contract itself holds $497,000 worth of different ERC20 tokens - all these tokens are permanently "stuck" inside the contract and therefore uselessly lost.*

### Recommendation

A simple "ERC20-rescue" function can solve the problem.

```js
interface IERC20 {
  function transfer(address _to, unit _amount);
}

function rescueERC20(address _token, uint256 _amount) external onlyOwner {
    IERC20(_token).transfer(owner(), _amount);
  }
```


## 3.2. Function includeInReward() waste a Gas and has a risk of `OUT_OF_GAS` exception.

### Severity: medium

### Description

The function `includeInReward()`(lines 400-411) use the loop `for()` to find and remove address from the `_excludedFromReward` list. It requires a lot of Gas if many addresses are excluded. In the case of the long excluded list, the function will be aborted with `OUT_OF_GAS` exception.

### Recommendation

Use [EnumerableSet](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/structs/EnumerableSet.sol) instead of address array (line 204). So you could remove record using function [remove()](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/243adff49ce1700e0ecb99fe522fb16cff1d1ddc/contracts/utils/structs/EnumerableSet.sol#L157).

## 3.3. Function _getCurrentSupply() has a risk of `OUT_OF_GAS` exception.

### Severity: medium

### Description

The function `_getCurrentSupply()`(lines 361-371) use the loop `for()`(lines 364-368) to calculate `reflectedSupply` and `tokenSupply` values. In the case of the big length of `_excludedFromReward` list, this function will be aborted with `OUT_OF_GAS` exception. Since this function used in most other functions, the performance of the entire contract will be broken.
The risk becomes a higher due Gas cost of storage reading that may grow in future node updates. For example, after applying the EIP-1884 the cost of [the SLOAD (0x54) operation changes from 200 to 800 gas](https://eips.ethereum.org/EIPS/eip-1884). And in [EIP-2929](https://eips.ethereum.org/EIPS/eip-2929) discussing to increase the gas cost of `SLOAD (0x54)` to 2100.
This means that even if with current `_excludedFromReward` list length contract works now, it may stop works in the future when the cost of storage reading will change.

### Recommendation

1. Try to avoid long loops. 
2. Add limitation of `_excludedFromReward` list growing into function `excludeFromReward()`(lines 391-398):

```Solidity
require(_excludedFromReward.length < 50, "Excluded list too long");

```

## 3.4 Owner privileges

### Severity: owner privileges

### Description

- Owner can include (line 400) and exclude (line 391) any account to/from reward.
- Owner can include (line 387) and exclude (line 382) any account to/from fees.

# 4. Conclusion

The audited smart contract must not be deployed. Reported issues must be fixed prior to the usage of this contract.

**Comment by Wildfire-new** [comment]
https://github.com/Wildfire-new/Wildfirebeb20fix/blob/main/Wildfire.sol fixed bro
