### ISSUE TITLE
SHUSKY

### ISSUE THREAD

**Issue by SerecThunderson** [EthereumCommonwealth/Auditing#501]
# Audit request

SHUSKY (Siberian Husky) is a decentralized community token and store of value.
50% burned, 40% locked, 10% dumped on open market already, contract revoked

# Source code

https://etherscan.io/address/0x236d53148f83706c3d670064809577385f923a75#code

# Disclosure policy

Talk to me first in case it is a misunderstanding, but publish it later

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

admin@SHUSKYTOKEN.com T.me/serecthunderson

https://SHUSKYTOKEN.com
https://twitter.com/SHUSKYTOKEN
https://t.me/SHUSKYTOKEN
https://reddit.com/r/SHUSKYTOKEN
https://discord.gg/XGPhdcp9nA

# Platform

ETH

**Comment by yuriy77k** [comment]
@SerecThunderson  The audit fee is 672 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 5 days after payment.

**Comment by SerecThunderson** [comment]
https://etherscan.io/tx/0x591b63076e1487946af55c7089a57091115277adec845f3fd653bb9d3e1f1404

**Comment by SerecThunderson** [comment]
Thank you kindly for the service.

**Comment by yuriy77k** [comment]
# SHUSKY Security Audit Report

# 1. Summary

[SHUSKY](https://etherscan.io/address/0x236d53148f83706c3d670064809577385f923a75#code) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

- https://SHUSKYTOKEN.com
- https://twitter.com/SHUSKYTOKEN
- https://t.me/SHUSKYTOKEN
- https://reddit.com/r/SHUSKYTOKEN
- https://discord.gg/XGPhdcp9nA

# 2. In scope

https://etherscan.io/address/0x236d53148f83706c3d670064809577385f923a75#code

# 2.1 Excluded

The correctness of the mathematical calculations was not verified during the audit due to the lack of complete documentation of what the contract should do and under what conditions.

# 3. Findings

In total, **4 issues** were reported including:

- 2 medium severity issues.

- 1 low severity issues.

- 1 owner privileges.


## 3.1. Known vulnerabilities of ERC-20 and BEP-20 token

### Severity: low

### Description

1. Lack of transaction handling mechanism issue. [WARNING!](https://gist.github.com/Dexaran/ddb3e89fe64bf2e06ed15fbd5679bd20)  This is a very common issue and it already caused millions of dollars losses for lots of token users! More details [here](https://docs.google.com/document/d/1Feh5sP6oQL1-1NHi-X1dbgT3ch2WdhbXRevDN681Jv4/edit).

### Recommendation

Add the following code to the `transfer(_to address, ...)` function:

```
require( _to != address(this) );

```

2. ERC20 is a widely used standard across the Ethereum ecosystem. It is reasonable to assume that ERC20 tokens could be "accidentally" deposited into this contract even though it is not intentional.

Every user on the entire Ethereum ecosystem can send ERC20 tokens to this contract and he will have no ability to extract it back unless there is a special "ERC20-rescue" function implemented in your contract. It is advised to implement this function.

*Example: here is [BAT contract address](https://etherscan.io/address/0x0d8775f648430679a709e98d2b0cb6250d2887ef). As you can see the contract itself holds $497,000 worth of different ERC20 tokens - all these tokens are permanently "stuck" inside the contract and therefore uselessly lost.*

### Recommendation

A simple "ERC20-rescue" function can solve the problem.

```js
function rescueERC20(address _token, uint256 _amount) external onlyOwner {
    IERC20(_token).transfer(owner(), _amount);
  }
```


## 3.2. Function includeAccount() waste a Gas and has a risk of `OUT_OF_GAS` exception.

### Severity: medium

### Description

The function `includeAccount()`(lines 400-411) use the loop `for()` to find and remove address from the `_excluded` list. It requires a lot of Gas if many addresses are excluded. In the case of the long excluded list, the function will be aborted with `OUT_OF_GAS` exception.

### Recommendation

Use [EnumerableSet](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/structs/EnumerableSet.sol) instead of address array (line 500). So you could remove record using function [remove()](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/243adff49ce1700e0ecb99fe522fb16cff1d1ddc/contracts/utils/structs/EnumerableSet.sol#L157).

## 3.3. Function _getCurrentSupply() has a risk of `OUT_OF_GAS` exception.

### Severity: medium

### Description

The function `_getCurrentSupply()`(lines 731-741) use the loop `for()`(lines 734-738) to calculate `rSupply` and `tSupply` values. In the case of the big length of `_excluded` list, this function will be aborted with `OUT_OF_GAS` exception. Since this function used in most other functions, the performance of the entire contract will be broken.
The risk becomes a higher due Gas cost of storage reading that may grow in future node updates. For example, after applying the EIP-1884 the cost of [the SLOAD (0x54) operation changes from 200 to 800 gas](https://eips.ethereum.org/EIPS/eip-1884). And in [EIP-2929](https://eips.ethereum.org/EIPS/eip-2929) discussing to increase the gas cost of `SLOAD (0x54)` to 2100.
This means that even if with current `_excluded` list length contract works now, it may stop works in the future when the cost of storage reading will change.

### Recommendation

1. Try to avoid long loops. 
2. Add limitation of `_excluded` list growing into function `excludeAccount()`(lines 615-617):

```Solidity
require(_excluded.length < 50, "Excluded list too long");

```

## 3.4 Owner privileges

### Severity: owner privileges

### Description

- Owner can include (line 624) and exclude (line 615) any account.

# 4. Conclusion

The audited smart contract must not be deployed. Reported issues must be fixed prior to the usage of this contract.

**Comment by SerecThunderson** [comment]
Hello, we would like to bring contention to a couple of points:

**3.4 Owner privileges**
This is not a security issue, because the ownership of this contract has already been revoked to a burn address, and cannot be redeemed.

**3.2. Function includeAccount() waste a Gas and has a risk of OUT_OF_GAS exception.**
This is not a gas issue, because the function is only inefficient when the list of excluded accounts is large. Because there is no, and never will be, an owner to add accounts to the excluded list, this can never grow to be a gas issue.

We understand the reasonings for the judgements, and also agree with and understand the rest of the audit in entirety.
But it is important that the issues above be addressed, please.

**Comment by yuriy77k** [comment]
@SerecThunderson thank you for your notice. The report was updated.

**Comment by yuriy77k** [comment]
Blog post:
https://callisto.network/shusky-security-audit/

Twitter:
https://twitter.com/Callisto_Audits/status/1396163989986545665

Twitter FR:
https://twitter.com/CallistoNetFr/status/1396163982059315203

Twitter RU:
https://twitter.com/CallistoNetRu/status/1396163974270439424
