### ISSUE TITLE
Fixed Staking Contract Audit

### ISSUE THREAD

**Issue by giopaul** [EthereumCommonwealth/Auditing#574]
# Audit request

Smart contract is for staking purposes like 1,3,6,12 months locked staking. User will be able to stake the tokens before 'stakeStartDate' and unstaked tokens after 'stakeEndDate'. Reward percentage is calculated on monthly basis, but automatically it will multiple with (stakeEndDate - stakeStartDate ) 

# Source code

https://github.com/giopaul/defipii/blob/main/staking.sol

# Contact information (optional)

Email: gio.pauolz@gmail.com  

# Platform

BSC Network

**Comment by yuriy77k** [comment]
@giopaul the audit fee is 701 USDT.
You may send USDT (ERC20 or BEP20) to: 0xb9662e592f2f0412be62f0833ca463a9b1aabebb
or USDT (TRC20) to: TBzUKbek9AYVBwf91ykh3KY4Ushk95SCiB

The estimated auditing time - 7 days after payment.

**Comment by giopaul** [comment]
@yuriy77k Payment transferred from my side. Please cross check it from your side and proceed. 

Mode: TRC20
TxtId:  722a620326cd5fd7bc5f9132f689a9436b8788e5c7032353a5dcfad983302c96

**Comment by yuriy77k** [comment]
@giopaul money received. Thank you.

**Comment by giopaul** [comment]
@yuriy77k Any update?

**Comment by yuriy77k** [comment]
@giopaul the contract has high severity issues. The report was sent to your email.

**Comment by giopaul** [comment]
Hello @yuriy77k , hope you are doing good!!
Today, I just deployed contract on BSC Explorer and used write function for stake but it showing transaction suggesting fee  0.47 BNB, that is too high. Can you please suggest anything for it?  

Reference Link: ( https://bscscan.com/address/0x5C4a687251952bA50322DB9e386E9eCC406D4fbF#writeContract )

**Comment by yuriy77k** [comment]
I think the issue is in the parameters that you are using in the constructor on deployment.
```
Arg [2] : _minStake (uint256): 100
Arg [3] : _maxStake (uint256): 100000000
Arg [4] : _stakeStartDate (uint256): 1637712001000
Arg [5] : _stakeEndDate (uint256): 1637884801000
```
To stake, the staking amount should be less than `MAX_STAKE_AMOUNT` but its value was set to 100000000 = 0.0000000001 WARRIOR token (it has 18 decimals). So you will stake more than this value - the transaction will fail.
If you need to set `_minStake` to 100 tokens you have to set it to 100 * 10**18 and for `_maxStake` for 100000000 tokens you should multiply it by 10**18 as well.

The second issue in the `_stakeStartDate` and `_stakeEndDate`. The smart contract uses the timestamp in seconds but you set it in milliseconds (in 1000 times higher value). It will cause problems with unstake function (you could not unstake tokens in the next 52 thousand years).

**Comment by giopaul** [comment]
@yuriy77k 
Can you please check now?

( https://bscscan.com/address/0x4fad414611EC7B5f29edf5AEDBb0789FA28e4d17#writeContract )

**Comment by yuriy77k** [comment]
Now it looks good.
minStake = 100 tokens, maxStake = 10000 tokens
stake start date = 29 November 2021, 05:30:00 UTC
stake end date = 1 December 2021, 05:30:00 UTC
