### ISSUE TITLE
DappVolume.com Audit

### ISSUE THREAD

**Issue by dappvolume** [EthereumCommonwealth/Auditing#8]
# Audit request

DappVolume is a platform that showcases Dapps.  The platform currently has 3 smart contracts.  These contracts handle setting the username, setting website, liking dapps, advertising, investing, and payouts.  There is some more info on how the contracts work on the home page of DappVolume near the bottom.  Thank you.

https://dappvolume.com

# Source code

https://github.com/dappvolume/smart-contracts

OR on Etherscan:

Profile username and website contract
https://etherscan.io/address/0x8bd3eb9328d371ef2e4a4da1b0e879043f13612e

Dapp Likes contract
https://etherscan.io/address/0x6acd16200a2a046bf207d1b263202ec1a75a7d51

Advertiser and Investor contract
https://etherscan.io/address/0xdd8f1fc3f9eb03e151abb5afcc42644e28a1e797

# Disclosure policy

If critical, please email us first wolf@dappvolume.com before publicly disclosing.

# Platform

ETH on live net

**Comment by RideSolo** [comment]
Auditing time: 7 days.

**Comment by yuriy77k** [comment]
@RideSolo assigned.

**Comment by gorbunovperm** [comment]
The estimated auditing time is 7 days.

**Comment by yuriy77k** [comment]
@MrCrambo @gorbunovperm assigned.

**Comment by MrCrambo** [comment]
@yuriy77k my report is done!

**Comment by gorbunovperm** [comment]
@yuriy77k My audit is finished!

**Comment by gorbunovperm** [comment]
@yuriy77k Please, look at my report again. One more vulnerability was discovered.

**Comment by yuriy77k** [comment]
@gorbunovperm Very good job!

**Comment by yuriy77k** [comment]
I send email with updated audit report to wolf@dappvolume.com
By our policy, we may public this report at 15 days after informing contract owner.

**Comment by yuriy77k** [comment]
# [DappVolume.com](https://github.com/dappvolume/smart-contracts) security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# Conclusion:

One high severity issue and one medium issue was highlighted. It is necessary to fix it.

This contract is **not safe** to be used, the above mentioned issue can lead to conflict with the investors. The project team has to solve this problem.

# 1. High severity issues:

## 1.1. A malicious user can to remain an investor forever.

####  [Code snippet](https://github.com/dappvolume/smart-contracts/blob/f95df2c546ff2d175adc3854c75e365377ca0ba4/dappVolumeAd.sol#L137-L140)

```Solidity
function updateInvestor() public payable {
    require(msg.value >= investmentMin);
    theInvestor.transfer(msg.value.div(100).mul(60)); // send 60% to last investor (120% of original purchase)
    theInvestor = msg.sender; // set new investor
    investmentMin = investmentMin.mul(2); // double the price to become the investor
}
```

#### Description

An malicious user can become an investor forever. To do this, he needs to write an attacking smart contract. The contract will `throw` when a potential new investor will send reward to malicious investor. In this case `updateInvestor()` method will never be fulfilled again.

Example code of attacker smart contract:

```solidity
contract adContract {
    function updateInvestor() public payable;
}

contract attacker {
    function () payable {
      require(msg.value < 76800000000000000);
    }

    function lifelongInvestor(address adr) payable {
        adContract(adr).updateInvestor.value(msg.value)();
    }
}
```

The attacker calculates that he needs to become the 7th investor. And at the right moment it calls the `lifelongInvestor()` function. Then a potential new investor must pay him a reward of `0.0768 Ether`. If the amount of payment is suitable for this condition, then the attacker will cancel this payment. Thus, endlessly receiving a reward for advertising.

Explanation of figures:
* The biggest reward for an investor from advertising is `adPriceWeek / 10 = 0.05 Ether`. It is may be more, but for simplicity it's good amount.
* To become the 8th investor, the user must pay `investmentMin * 2^7 = 0.128 Ether`. And the reward to the previous investor will be `0.128 / 100 * 60 = 0.0768 Ether`.

## 1.2. A malicious user can block voting.

#### Description

This issue is a similar as issue 1.1, but a malicious user can block voting system if `throw` the transfer to his address ```lastAddress.transfer(msg.value.div(2));```.

### Code snippet

https://github.com/dappvolume/smart-contracts/blob/f95df2c546ff2d175adc3854c75e365377ca0ba4/dappVolumeHearts.sol#L86


## 1.3. A malicious user can block advertising function.

#### Description

This issue is a similar as issue 1.1, but a malicious user can block advertising system if `throw` the transfer to his address ```lastOwner.transfer(msg.value.div(2));```.

### Code snippet

https://github.com/dappvolume/smart-contracts/blob/f95df2c546ff2d175adc3854c75e365377ca0ba4/dappVolumeAd.sol#L126


# 2. Medium severity issues:

## 2.1. Return on Investment (misleading definition)

### Description

Concerning the function `updateInvestor` member of `dappVolumeAd` contract, and as advertised in the website "An investor can get bought out by a bigger investor and will get 120% of their investment back".

The implementation of the function doesn't reflect the above mentioned definition. if an investor invests more ethers than `investmentMin` state variable, and the next investor invests the exact required amount the first investor will not get 120% of his investment back but less (the percentage will depend on its payment).

The opposite is also true, an investor can get more than 120% of his ethers back if the next investor sends more than the required amount.

### Code snippet

https://github.com/dappvolume/smart-contracts/blob/f95df2c546ff2d175adc3854c75e365377ca0ba4/dappVolumeAd.sol#L136#L141


# 3. Low severity issues:

## 3.1. Lost Ether

### Description

`lastAddress` member of `dappVolumeHearts` contract, is not set in the constructor. This issue lead to lose the first half of the ethers sent using `update` function member of the same contract. 
Half of the ethers sent will go to the address 0x0, however this issue will concern only the first transaction.

### Recommendation

Set the `lastAddress` to the owner address when creating the contract.

### Code snippet

https://github.com/dappvolume/smart-contracts/blob/f95df2c546ff2d175adc3854c75e365377ca0ba4/dappVolumeHearts.sol#L82#L88


## 3.2. dappId Requirement 

### Description

In order for a dapp to be advertised the `id` input for the function `updateAd` has to be higher than zero (`dappVolumeAd` contract), the same requirement is not applied in order for a dapp to be liked in function `update` member of `dappVolumeHearts`.

### Code snippet

https://github.com/dappvolume/smart-contracts/blob/f95df2c546ff2d175adc3854c75e365377ca0ba4/dappVolumeHearts.sol#L82#L88
https://github.com/dappvolume/smart-contracts/blob/f95df2c546ff2d175adc3854c75e365377ca0ba4/dappVolumeAd.sol#L106#L133


# 4. Minor observation.

## 4.1. Unnecessary Use of Require

### Description

In `setAccountNickname` and `setAccountUrl` functions members of `dappVolumeProfile` contract, the use or `require` to check if the message sender address is different than 0x0 address is unnecessary. This is just adding extra computation and gas consumption since `msg.sender` cannot be equal to 0x0.

### Code snippet

https://github.com/dappvolume/smart-contracts/blob/f95df2c546ff2d175adc3854c75e365377ca0ba4/dappVolumeProfile.sol#L9
https://github.com/dappvolume/smart-contracts/blob/f95df2c546ff2d175adc3854c75e365377ca0ba4/dappVolumeProfile.sol#L15


## 4.2. Old solidity version. 

#### Description

Used solidity version in [dappVolumeProfile.sol](https://github.com/dappvolume/smart-contracts/blob/master/dappVolumeProfile.sol) is old. 

## 4.3. Write a transfer operation at the end of function is good practice.

#### Description

Move [transfer](https://github.com/dappvolume/smart-contracts/blob/f95df2c546ff2d175adc3854c75e365377ca0ba4/dappVolumeAd.sol#L138) method call after [investmentMin](https://github.com/dappvolume/smart-contracts/blob/f95df2c546ff2d175adc3854c75e365377ca0ba4/dappVolumeAd.sol#L140) variable update.



# Revealing audit reports:

https://gist.github.com/RideSolo/f1e99c8dbb8f936bbf5c160721e93364

https://gist.github.com/MrCrambo/d7cefec3da09e77e747c45a983a668e9

https://gist.github.com/gorbunovperm/e6378cef9f60f4dda73b96709061633c
