### ISSUE TITLE
cryptonity audit

### ISSUE THREAD

**Issue by Katsiaryna-Maslava** [EthereumCommonwealth/Auditing#9]
# Audit request

Cryptonity Smart Contract Informations :

Initial Coin Offering rules and details:

Our Token Sale will be done in multiple cryptocurrencies such as:
Bitcoin, Ethereum, Bitcoin Cash and Litecoin. (may be subject to change)

We will also accept fiat throught debit card and bank transfer, the minimum and maximum amount will be available on the ICO website. (may be subject to change)
Our Token Sale will be opened for 60 days. (may be subject to change)

All investors will need to complete their «Know Your Customer» (KYC) registration before they will be able to withdraw their tokens.

Token name Cryptonity, with the ticker XNY.

TOTAL SUPPLY : 100 Millions tokens.

Cryptonity Token Allocation is detailed here:

•    60MM Cryptonity Tokens for our public token sale.
•    10MM Cryptonity Tokens for our official Airdrop and Bounty Program.
•    20MM Cryptonity Tokens will be kept by the Cryptonity Team.
•    3MM Cryptonity Tokens will be allocated to our Advisors.
•    7MM Cryptonity Tokens will serve as insurance.

Cryptonity Token will run natively on the Ethereum Blockchain.

Prices, dates and bonus informations :

Soft Cap : 500.000 $ 
Hard Cap Maximum : 20.120.000 $
Public sale phase 1 : Start 1 November 13 Pm ( Paris GMT +1 )
10 MM tokens + 50 % bonus = 15 MM tokens
Token Price : 0.23 $ 
Total sale Phase 1 : 2.300.000 $
Public sale phase 2 : Start 1 December 13 Pm ( Paris GMT +1 )
20 MM tokens + 30 % bonus = 26 MM tokens
Token Price : 0.34 $ 
Total sale Phase 2 : 6.800.000 $
Public sale phase 3 : Start 15 December 13 Pm ( Paris GMT +1 ) 
17 MM tokens + 15 % bonus = 19 MM tokens
Token Price : 0.58 $ 
Total sale Phase 3 : 11.020.000 $
Public sale Close : End 31 December 13 Pm ( Paris GMT +1 ) or whenever coins are sold out.

60MM Cryptonity Tokens for our public token sale.

WALLET ADRESSES TO INCLUDE IN SMART CONTRACT :

WE WILL GIVE YOU ALL THIS INFOS BEFORE DEPLOY CONTRACT ON MAINNET.

Cryptonity token not launched is was the case no need smart contract

No integration of Fiat for the moment

Yes people will be able to buy our token in our ICO website, only token price at stage sale need to be converted in crypto user want to buy with, ETH BTC BCH etc, there is a calculator in website we just need adjust our data

# Source code

[cryptonity](https://github.com/Katsiaryna-Maslava/cryptonity)

# Disclosure policy

m.suhlob@invatechs.com

# Platform

ethereum (ropsten)

**Comment by RideSolo** [comment]
Auditing time: 7 days.

**Comment by alexo18** [comment]
Auditing time: 7 days

**Comment by yuriy77k** [comment]
@RideSolo @alexo18  assigned.

**Comment by MrCrambo** [comment]
Auditing time 7 days.

**Comment by yuriy77k** [comment]
@MrCrambo assigned.

**Comment by gorbunovperm** [comment]
Estimated auditing time is 7 days.

**Comment by yuriy77k** [comment]
@gorbunovperm here are already 3 auditors, take next task for audit.

**Comment by yuriy77k** [comment]
@MrCrambo please, paused auditing this contract and make audit #11
We need complete it in two days.

**Comment by MrCrambo** [comment]
@yuriy77k ok, then add me 1 more day for auditing this issue

**Comment by yuriy77k** [comment]
@MrCrambo ok

**Comment by yuriy77k** [comment]
This smart contract contain high severity issue and I send email with audit report to m.suhlob@invatechs.com
By our policy, we may public this report at 15 days after informing contract owner.

**Comment by yuriy77k** [comment]
# [Cryptonity Smart Contract](https://github.com/Katsiaryna-Maslava/cryptonity) security audit report performed by [Callisto Security Audit Department](https://github.com/EthereumCommonwealth/Auditing)

# 1. Conclusion:

This ICO is not safe to be deployed, the developers should update the code following the above highlighted security issues.

# 2. High severity issues:

## 2.1. Crowdsale Finalization Failing 

### Description

At the end of the execution of the reimplemented `finalization` function member of `CryptonityCrowdsale` contract, the token address used cannot accept `ownershipTransfert` since the `msg.sender` has to be the owner address. The token contract isn't created inside `CryptonityCrowdsale` contract, therefore the call to `finalize` function will throw and the ICO will fail.

### Code snippet

https://github.com/Katsiaryna-Maslava/cryptonity/blob/bc1b8e23c9881722d594beb82ac80c5ee8319218/flatContracts/FlatCryptonityCrowdsale.sol#L838

Same issue here due to duplicated contract:

https://github.com/Katsiaryna-Maslava/cryptonity/blob/bc1b8e23c9881722d594beb82ac80c5ee8319218/contracts/crowdsale/CryptonityCrowdsale.sol#L220

### Recommendation

Remove the the implicated code line.


# 3. Medium severity issues:

## 3.1. Investor Reward Computation 

### Description

The Token reward value when users decide to invest is dependent on ETH/USD rate exchange (look at `FiatContract`), the rate is set by the team and can be subject to manipulation (this is just a possibility where users reward can be manipulated). The users will have to trust the team to input the right rate, this can be a decisive point for both users safe investments and the project fund raising where it can have a positive or a negative impact for both sides (dev/investors).

### Code snippet

https://github.com/Katsiaryna-Maslava/cryptonity/blob/bc1b8e23c9881722d594beb82ac80c5ee8319218/contracts/crowdsale/FiatContract.sol#L87#L91

https://github.com/Katsiaryna-Maslava/cryptonity/blob/bc1b8e23c9881722d594beb82ac80c5ee8319218/contracts/crowdsale/CryptonityCrowdsale.sol#L115#L118

Same issue here due to duplicated contract:

https://github.com/Katsiaryna-Maslava/cryptonity/blob/bc1b8e23c9881722d594beb82ac80c5ee8319218/flatContracts/FlatCryptonityCrowdsale.sol#L744#L747

### Recommendation

A fully automated crowdsale phase, without external interaction can help investors to trust the ICO.


## 3.2. Goal Reached Condition 

### Description

The value returned by `goalreached` function depend on an external factors manually set by the team (ETH/USD rate), following the high volatility of the crypto markets the results of such function can be highly random. The possible errors are the following:

- If ETH/USD rate changes and the team update the rate after the finalization of the Crowdsale phase, `withdrawTokens()`call may fail since it requires `goalReached` to return `true`.
- The opposite is also true if the crowdsale goal isn't reached and finilized, if the rate change later the `claimRefund()` (member of OpenZepplin contracts framework) call may fail since it requires `goalReached` to return `false`.

### Code snippet

https://github.com/Katsiaryna-Maslava/cryptonity/blob/bc1b8e23c9881722d594beb82ac80c5ee8319218/flatContracts/FlatCryptonityCrowdsale.sol#L777#L779

https://github.com/Katsiaryna-Maslava/cryptonity/blob/bc1b8e23c9881722d594beb82ac80c5ee8319218/flatContracts/FlatCryptonityCrowdsale.sol#L816#L821

https://github.com/Katsiaryna-Maslava/cryptonity/blob/bc1b8e23c9881722d594beb82ac80c5ee8319218/flatContracts/FlatCryptonityCrowdsale.sol#L562#L567

Same issue here due to duplicated contract:

https://github.com/Katsiaryna-Maslava/cryptonity/blob/bc1b8e23c9881722d594beb82ac80c5ee8319218/contracts/crowdsale/CryptonityCrowdsale.sol#L148#L150

https://github.com/Katsiaryna-Maslava/cryptonity/blob/bc1b8e23c9881722d594beb82ac80c5ee8319218/contracts/crowdsale/CryptonityCrowdsale.sol#L198#L203


## 3.3. Possible setup to zero address. 

### Description

Tokens could be sent to zero address and owner can lose his access because of setting sender and creator address to `zero address`. Functions [`changeCreator`](https://github.com/Katsiaryna-Maslava/cryptonity/blob/bc1b8e23c9881722d594beb82ac80c5ee8319218/contracts/crowdsale/FiatContract.sol#L101) and [`changeSender`](https://github.com/Katsiaryna-Maslava/cryptonity/blob/bc1b8e23c9881722d594beb82ac80c5ee8319218/contracts/crowdsale/FiatContract.sol#L107).

### Recommendation

Need to check if address whe want to set is not zero address.


# 4. Low severity issues:

## 4.1. Incorrect Solidity version.

### Description

`FlatCryptonityCrowdsale` and `FlatCryptonityToken` contracts have "pragma solidity ^0.4.13;" but "constructor" keyword is available from 0.4.23 version. 

### Code snippet

https://github.com/Katsiaryna-Maslava/cryptonity/blob/bc1b8e23c9881722d594beb82ac80c5ee8319218/flatContracts/FlatCryptonityCrowdsale.sol#L1

https://github.com/Katsiaryna-Maslava/cryptonity/blob/bc1b8e23c9881722d594beb82ac80c5ee8319218/flatContracts/FlatCryptonityToken.sol#L1

### Recommendation

Replace  ```pragma solidity ^0.4.13;``` to ```pragma solidity ^0.4.23;```


# 5. Minor observation:

## 5.1. Possible wrong logic.

### Description

Function [changeSender(address _sender)](https://github.com/Katsiaryna-Maslava/cryptonity/blob/bc1b8e23c9881722d594beb82ac80c5ee8319218/contracts/crowdsale/FiatContract.sol#L107-L109) ```require(msg.sender==creator)```, but change ```sender``` address. Maybe there was ```require(msg.sender == sender)```?



# Revealing audit reports:

https://gist.github.com/yuriy77k/f24cade1d02e51deaffde6192dbc03fd

https://gist.github.com/yuriy77k/8ba6b05a5426d19eb1b389cd01eabe6b

https://gist.github.com/yuriy77k/8ba5efceb8e7214055be437373124220

**Comment by yuriy77k** [comment]
## @RideSolo

Notes regarding the https://gist.github.com/RideSolo/76b38d6fd63ac31f3d2b9596dbe002de report.

Your report is fine.


## @alexo18

Notes regarding the https://gist.github.com/alexo18/3a3c829f0200a69ca955b17f40822850 report.

* [block.timestamp forgeability](https://gist.github.com/yuriy77k/8ba6b05a5426d19eb1b389cd01eabe6b#1-blocktimestamp-forgeability) in not security issue. The time of crowdsale phase can not be exactly limited to a second, it's mostly estimate time.


## @MrCrambo 

Notes regarding the https://gist.github.com/MrCrambo/df97c6e3d24076b56d28f5014420182f report.

Your report is fine.
